name: Lines of code

on:
  workflow_dispatch

jobs:
  fetch-repos:
    runs-on: ubuntu-latest

   
    steps:
    - uses: 
    - name: Install dependencies
      run: |
        
        python -m pip install --upgrade pip
        pip install pytest

